server.port=8080

# ===============================
# DATABASE
# ===============================

spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# ===============================
# JWT
# ===============================

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

# ===============================
# EMAIL / SMTP
# ===============================

spring.mail.host=mail.iniyo.in
spring.mail.port=587
spring.mail.username=info@iniyo.in
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.test-connection=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.mail.from=info@iniyo.in
app.mail.from-name=INIYO